export const selecoesData = [
  { nome: "México", codigoIso: "MEX", grupo: "A", tecnico: "Javier Aguirre" },
  { nome: "África do Sul", codigoIso: "RSA", grupo: "A", tecnico: "Hugo Broos" },
  { nome: "República da Coreia", codigoIso: "KOR", grupo: "A", tecnico: "Hong Myung-bo" },
  { nome: "Tchéquia", codigoIso: "CZE", grupo: "A", tecnico: "Ivan Hašek" },
  { nome: "Suíça", codigoIso: "SUI", grupo: "B", tecnico: "Murat Yakin" },
  { nome: "Canadá", codigoIso: "CAN", grupo: "B", tecnico: "Jesse Marsch" },
  { nome: "Bósnia e Herzegovina", codigoIso: "BIH", grupo: "B", tecnico: "Sergej Barbarez" },
  { nome: "Catar", codigoIso: "QAT", grupo: "B", tecnico: "Tintín Márquez" },
  { nome: "Brasil", codigoIso: "BRA", grupo: "C", tecnico: "Dorival Júnior" },
  { nome: "Marrocos", codigoIso: "MAR", grupo: "C", tecnico: "Walid Regragui" },
  { nome: "Escócia", codigoIso: "SCO", grupo: "C", tecnico: "Steve Clarke" },
  { nome: "Haiti", codigoIso: "HAI", grupo: "C", tecnico: "Sébastien Migné" },
  { nome: "EUA", codigoIso: "USA", grupo: "D", tecnico: "Mauricio Pochettino" },
  { nome: "Austrália", codigoIso: "AUS", grupo: "D", tecnico: "Tony Popovic" },
  { nome: "Paraguai", codigoIso: "PAR", grupo: "D", tecnico: "Gustavo Alfaro" },
  { nome: "Turquia", codigoIso: "TUR", grupo: "D", tecnico: "Vincenzo Montella" },
  { nome: "Alemanha", codigoIso: "GER", grupo: "E", tecnico: "Julian Nagelsmann" },
  { nome: "Costa do Marfim", codigoIso: "CIV", grupo: "E", tecnico: "Emerse Faé" },
  { nome: "Equador", codigoIso: "ECU", grupo: "E", tecnico: "Sebastián Beccacece" },
  { nome: "Curaçao", codigoIso: "CUW", grupo: "E", tecnico: "Dick Advocaat" },
  { nome: "Holanda", codigoIso: "NED", grupo: "F", tecnico: "Ronald Koeman" },
  { nome: "Japão", codigoIso: "JPN", grupo: "F", tecnico: "Hajime Moriyasu" },
  { nome: "Suécia", codigoIso: "SWE", grupo: "F", tecnico: "Jon Dahl Tomasson" },
  { nome: "Tunísia", codigoIso: "TUN", grupo: "F", tecnico: "Jalel Kadri" },
  { nome: "Bélgica", codigoIso: "BEL", grupo: "G", tecnico: "Domenico Tedesco" },
  { nome: "Egito", codigoIso: "EGY", grupo: "G", tecnico: "Hossam Hassan" },
  { nome: "Irã", codigoIso: "IRI", grupo: "G", tecnico: "Amir Ghalenoei" },
  { nome: "Nova Zelândia", codigoIso: "NZL", grupo: "G", tecnico: "Darren Bazeley" },
  { nome: "Espanha", codigoIso: "ESP", grupo: "H", tecnico: "Luis de la Fuente" },
  { nome: "Cabo Verde", codigoIso: "CPV", grupo: "H", tecnico: "Bubista" },
  { nome: "Uruguai", codigoIso: "URU", grupo: "H", tecnico: "Marcelo Bielsa" },
  { nome: "Arábia Saudita", codigoIso: "KSA", grupo: "H", tecnico: "Roberto Mancini" },
  { nome: "França", codigoIso: "FRA", grupo: "I", tecnico: "Didier Deschamps" },
  { nome: "Noruega", codigoIso: "NOR", grupo: "I", tecnico: "Ståle Solbakken" },
  { nome: "Senegal", codigoIso: "SEN", grupo: "I", tecnico: "Pape Thiaw" },
  { nome: "Iraque", codigoIso: "IRQ", grupo: "I", tecnico: "Jesús Casas" },
  { nome: "Argentina", codigoIso: "ARG", grupo: "J", tecnico: "Lionel Scaloni" },
  { nome: "Áustria", codigoIso: "AUT", grupo: "J", tecnico: "Ralf Rangnick" },
  { nome: "Argélia", codigoIso: "ALG", grupo: "J", tecnico: "Vladimir Petković" },
  { nome: "Jordânia", codigoIso: "JOR", grupo: "J", tecnico: "Jamal Sellami" },
  { nome: "Colômbia", codigoIso: "COL", grupo: "K", tecnico: "Néstor Lorenzo" },
  { nome: "Portugal", codigoIso: "POR", grupo: "K", tecnico: "Roberto Martínez" },
  { nome: "RD do Congo", codigoIso: "COD", grupo: "K", tecnico: "Sébastien Desabre" },
  { nome: "Uzbequistão", codigoIso: "UZB", grupo: "K", tecnico: "Srečko Katanec" },
  { nome: "Inglaterra", codigoIso: "ENG", grupo: "L", tecnico: "Gareth Southgate" },
  { nome: "Croácia", codigoIso: "CRO", grupo: "L", tecnico: "Zlatko Dalić" },
  { nome: "Gana", codigoIso: "GHA", grupo: "L", tecnico: "Otto Addo" },
  { nome: "Panamá", codigoIso: "PAN", grupo: "L", tecnico: "Thomas Christiansen" },
];

export const jogadoresData: Record<string, { nome: string; posicao: string; numeroCamisa: number }[]> = {
  "MEX": [
    { nome: "Guillermo Ochoa", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "César Montes", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Johan Vásquez", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Israel Reyes", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Gerardo Arteaga", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Edson Álvarez", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Luis Chávez", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Carlos Rodríguez", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Raúl Jiménez", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Alexis Vega", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Santiago Giménez", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Luis Malagón", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Jorge Sánchez", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Érick Gutiérrez", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Jesús Gallardo", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Kevin Álvarez", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Orbelín Pineda", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Andrés Guardado", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Sebastián Córdova", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Erick Sánchez", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Uriel Antuna", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Roberto Alvarado", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "José Rangel", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Hirving Lozano", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Luis Romo", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Henry Martín", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "RSA": [
    { nome: "Ronwen Williams", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Nyiko Mobbie", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Skhumbuzo Ncgobo", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Mothobi Mvala", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Sifiso Hlanti", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Teboho Mokoena", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Luke Le Roux", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Sphephelo Sithole", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Percy Tau", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Themba Zwane", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Lyle Foster", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Veli Mothwa", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Katlego Mohamme", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Nkosinathi Sibisi", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Innocent Maela", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Grant Kekana", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Mondli Mbanjwa", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Thabang Monare", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Yusuf Maart", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Thapelo Maseko", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Evidence Makgopa", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Oswin Appolis", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Ricardo Goss", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Iqraam Rayners", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Jayden Adams", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Mihlali Mayambela", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "KOR": [
    { nome: "Kim Seung-gyu", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Kim Min-jae", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Kim Young-gwon", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Seol Young-woo", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Jung Seung-hyun", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Hwang In-beom", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Son Heung-min", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Lee Kang-in", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Cho Gue-sung", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Lee Jae-sung", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Hwang Hee-chan", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Jo Hyeon-woo", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Lee Ki-je", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Kim Tae-hwan", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Park Jin-seop", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Kwon Kyung-won", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Paik Seung-ho", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Lee Soon-min", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Yang Hyun-jun", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Hong Hyun-seok", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Oh Hyeon-gyu", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Bae Jun-ho", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Song Bum-keun", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Na Sang-ho", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Jung Woo-young", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Um Won-sang", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "CZE": [
    { nome: "Jindřich Staněk", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "David Zima", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Tomáš Holeš", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Jakub Brabec", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Vladimír Coufal", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Tomáš Souček", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Antonín Barák", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Alex Král", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Patrik Schick", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Jan Kuchta", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Michael Krmenčík", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Tomáš Koubek", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Jaroslav Zelený", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Ladislav Krejčí", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Michal Sadílek", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "David Jurásek", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Lukáš Provod", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Michal Ševčík", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Pavel Šulc", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Václav Černý", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Mojmír Chytil", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Tomáš Čvančara", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Matěj Kovář", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Adam Hložek", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Ondřej Lingr", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Matěj Jurásek", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "SUI": [
    { nome: "Yann Sommer", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Manuel Akanji", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Silvan Widmer", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Nico Elvedi", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Ricardo Rodríguez", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Denis Zakaria", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Breel Embolo", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Remo Freuler", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Haris Seferović", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Xherdan Shaqiri", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Ruben Vargas", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Jonas Omlin", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Eray Cömert", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Cédric Zesiger", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Gregory Wüthrich", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Bećir Omeragić", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Fabian Rieder", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Djibril Sow", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Ardon Jashari", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Michel Aebischer", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Noah Okafor", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Andi Zeqiri", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Gregor Kobel", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Zeki Amdouni", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Filip Ugrinic", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Dan Ndoye", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "CAN": [
    { nome: "Milan Borjan", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Alistair Johnston", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Kamal Miller", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Dominick Zator", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Sam Adekugbe", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Samuel Piette", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Alphonso Davies", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Ismaël Koné", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Cyle Larin", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Jonathan David", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Tajon Buchanan", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Maxime Crépeau", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Richie Laryea", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Zakary McGillivray", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Joel Waterman", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Derek Cornelius", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Stephen Eustáquio", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Mathieu Choinière", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Mark-Anthony Kaye", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Jonathan Osorio", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Liam Millar", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Jacob Shaffelburg", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Dayne St. Clair", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Ike Ugbo", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Nicolas Gioacchini", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Theo Corbeanu", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "BIH": [
    { nome: "Ibrahim Šehić", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Jusuf Gazibegović", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Sead Kolašinac", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Ermin Bičakčić", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Nihad Mujakić", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Rade Krunić", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Miralem Pjanić", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Amir Hadžiahmetović", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Edin Džeko", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Haris Tabaković", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Ermedin Demirović", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Kenan Pirić", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Amar Dedić", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Dennis Hadžikadunić", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Adrian Barisic", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Nikola Katić", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Benjamin Tahirović", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Haris Hajradinović", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Miroslav Stevanović", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Mario Vrančić", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Smail Prevljak", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Adnan Šećerović", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Osman Hadžikić", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Kenan Kodro", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Sanjin Prcić", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Andrej Đokanović", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "QAT": [
    { nome: "Saad Al-Sheeb", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Pedro Miguel", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Al-Mahdi Ali", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Mohammed Waad", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Tarek Salman", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Abdulaziz Hatem", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Ahmed Fathy", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Ali Assadalla", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Almoez Ali", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Hassan Al-Haydos", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Akram Afif", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Yousof Hassan", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Musaab Kheder", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Homam Ahmed", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Bassam Al-Rawi", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Jassem Gaber", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Mostafa Meshaal", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Jassem Al-Hamad", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Naif Al-Hadhrami", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Abdullah Al-Ahrak", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Mohanad Ali", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Ismail Mohamad", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Salah Zakaria", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Khalid Muneer", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Ahmed Al-Ganehi", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Yusuf Abdurisag", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "BRA": [
    { nome: "Alisson", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Danilo", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Marquinhos", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Gabriel Magalhães", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Éder Militão", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Casemiro", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Bruno Guimarães", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Lucas Paquetá", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Richarlison", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Neymar", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Raphinha", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Bento", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Wendell", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Gleison Bremer", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Yan Couto", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Lucas Beraldo", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "André", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "João Gomes", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Douglas Luiz", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Andreas Pereira", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Vinícius Júnior", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Rodrygo", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Ederson", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Gabriel Martinelli", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Endrick", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Luiz Henrique", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "MAR": [
    { nome: "Yassine Bounou", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Achraf Hakimi", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Noussair Mazraoui", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Nayef Aguerd", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Romain Saïss", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Sofyan Amrabat", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Bilal El Khannouss", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Azzedine Ounahi", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Ayoub El Kaabi", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Hakim Ziyech", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Youssef En-Nesyri", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Munir Mohamedi", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Achraf Dari", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Yahia Attiyat Allah", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Chadi Riad", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Mohamed Chibi", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Selim Amallah", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Ilias Chair", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Zakaria Aboukhlal", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Ismael Saibari", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Amine Adli", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Ezgjan Alioski", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Reda Tagnaouti", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Sofiane Boufal", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Oussama El Azzouzi", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Eliesse Ben Seghir", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "SCO": [
    { nome: "Angus Gunn", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Anthony Ralston", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Andrew Robertson", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Grant Hanley", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Kieran Tierney", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Callum McGregor", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "John McGinn", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Billy Gilmour", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Che Adams", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Ryan Christie", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Lawrence Shankland", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Craig Gordon", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Jack Hendry", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Liam Cooper", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Scott McKenna", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Greg Taylor", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Scott McTominay", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Ryan Jack", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Lewis Ferguson", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Stuart Armstrong", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "James Forrest", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Ben Doak", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Liam Kelly", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Tommy Conway", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Kenny McLean", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Kevin Nisbet", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "HAI": [
    { nome: "Johny Placide", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Carlens Arcus", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "François Dulysse", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Ricardo Adé", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Martin Expérience", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Leverton Pierre", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Bryan Alceus", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Pheral Mabiala", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Duckens Nazon", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Frantzdy Pierrot", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Carnejy Antoine", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Alexandre Pierre", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Djimy Alexis", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Nathan François", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Woodensky Cherenfant", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Michenel Nehemie", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Bendy Joachim", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Dutherson Clerveaux", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Steeve Fénélus", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Jean Philippeaux", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Danley Jean-Louis", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Yves Desmarets", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Garry Sifrard", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Sony Nordé", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Pierre Bellevue", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Christofer Abraham", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "USA": [
    { nome: "Matt Turner", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Sergiño Dest", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Chris Richards", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Tim Ream", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Joe Scally", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Tyler Adams", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Giovanni Reyna", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Weston McKennie", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Ricardo Pepi", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Christian Pulisic", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Brenden Aaronson", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Ethan Horvath", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Cameron Carter-Vickers", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Mark McKenzie", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Kristoffer Lund", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Marlon Fossey", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Yunus Musah", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Luca de la Torre", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Malik Tillman", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Johnny Cardoso", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Folarin Balogun", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Timothy Weah", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Patrick Schulte", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Josh Sargent", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Aidan Morris", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Haji Wright", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "AUS": [
    { nome: "Mathew Ryan", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Miloš Degenek", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Harry Souttar", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Kye Rowles", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Aziz Behich", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Jackson Irvine", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Connor Metcalfe", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Riley McGree", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Jamie Maclaren", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Martin Boyle", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Mitchell Duke", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Joe Gauci", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Jordan Bos", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Alessandro Circati", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Fran Karačić", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Lewis Miller", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Keanu Baccus", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Aiden O'Neill", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Cameron Devlin", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Daniel Arzani", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Mathew Leckie", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Brandon Borrello", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Tom Glover", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Kusini Yengi", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Patrick Yazbek", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Nestory Irankunda", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "PAR": [
    { nome: "Carlos Miguel", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Gustavo Gómez", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Omar Alderete", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Fabián Balbuena", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Alan Núñez", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Richard Sánchez", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Diego Gómez", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Mathías Villasanti", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Antonio Sanabria", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Ángel Romero", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Julio Enciso", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Jean Fernandes", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Blas Riveros", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Juan Escobar", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Gustavo Velázquez", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Santiago Rojas", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Héctor Martínez", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Andrés Cubas", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Álvaro Campuzano", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Damián Bobadilla", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Ramón Sosa", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Derlis González", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Antony Silva", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Óscar Cardozo", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Jorge Morel", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Alex Arce", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "TUR": [
    { nome: "Mert Günok", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Zeki Çelik", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Merih Demiral", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Çağlar Söyüncü", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Abdülkerim Bardakcı", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Hakan Çalhanoğlu", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Kerem Aktürkoğlu", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Orkun Kökçü", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Cenk Tosun", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Yusuf Yazıcı", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Barış Alper Yılmaz", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Uğurcan Çakır", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Kaan Ayhan", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Samet Akaydın", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Ferdi Kadıoğlu", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Rıdvan Yılmaz", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "İsmail Yüksek", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Salih Özcan", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "İrfan Can Kahveci", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Okay Yokuşlu", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Enes Ünal", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Kenan Yıldız", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Altay Bayındır", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Umut Nayir", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Arda Güler", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Bertuğ Yıldırım", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "GER": [
    { nome: "Manuel Neuer", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Joshua Kimmich", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Antonio Rüdiger", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Jonathan Tah", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Benjamin Henrichs", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Toni Kroos", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Kai Havertz", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Jamal Musiala", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Niclas Füllkrug", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Leroy Sané", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Florian Wirtz", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Marc-André ter Stegen", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Robin Koch", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "David Raum", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Nico Schlotterbeck", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Malick Thiaw", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Robert Andrich", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Aleksandar Pavlović", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Pascal Groß", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Julian Brandt", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Thomas Müller", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Serge Gnabry", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Oliver Baumann", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Deniz Undav", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "İlkay Gündoğan", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Chris Führich", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "CIV": [
    { nome: "Yahia Fofana", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Willy Boly", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Evan Ndicka", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Odilon Kossounou", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Sergio Aurab", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Seko Fofana", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Jérémie Boga", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Franck Kessié", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Jonathan Bamba", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Wilfried Zaha", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Karim Konaté", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Badra Ali Sangaré", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Emmanuel Agbadou", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Ismaël Diallo", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Hassane Kamara", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Christopher Opéri", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Hamed Traorè", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Ibrahim Sangaré", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Jean-Daniel Beka", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Jean-Louis Komenan", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Sébastien Haller", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Simon Adingra", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Charles Folly", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Oumar Diakité", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Ângelo Fernando", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Max Gradel", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "ECU": [
    { nome: "Alexander Domínguez", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Félix Torres", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Piero Hincapié", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Willian Pacho", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Ángelo Preciado", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Alan Franco", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Moisés Caicedo", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Carlos Gruezo", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Kevin Rodríguez", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Gonzalo Plata", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Enner Valencia", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Hernán Galíndez", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Jackson Porozo", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Luis Fernando León", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Diego Palacios", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Andrés Micolta", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Jeremy Sarmiento", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Joao Ortiz", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Jhegson Méndez", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Kendry Páez", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Jordy Caicedo", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Leonardo Campana", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Moisés Ramírez", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Darwin Machís", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Oscar Zambrano", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Jhon Jairo Cifuentes", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "CUW": [
    { nome: "Eloy Room", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Cuco Martina", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Darryl Sher", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Jurien Gaari", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Geronimo Sambo", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Leandro Bacuna", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Michael Maria", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Vurnon Anita", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Richairo Živković", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Rangelo Janga", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Nigel Hasselbaink", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Tyrone Conraad", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Nathaniël Pietersz", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Serginho Doran", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Shurendro Grootfaam", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Wesley Martha", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Jearl Margaritha", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Xander Severina", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Gillian Arts", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Yurick Sebare", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Kenji Gorré", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Jarchinio Antonia", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Raoul Martijn", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Divjane Rojer", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Ronan Kerssies", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Archangelo Martina", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "NED": [
    { nome: "Bart Verbruggen", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Lutsharel Geertruida", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Matthijs de Ligt", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Virgil van Dijk", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Nathan Aké", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Frenkie de Jong", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Memphis Depay", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Teun Koopmeiners", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Wout Weghorst", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Steven Bergwijn", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Cody Gakpo", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Mark Flekken", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Denzel Dumfries", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Stefan de Vrij", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Jurriën Timber", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Quilindschy Hartman", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Ryan Gravenberch", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Mats Wieffer", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Kenneth Taylor", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Joey Veerman", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Donyell Malen", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Xavi Simons", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Justin Bijlow", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Brian Brobbey", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Jerdy Schouten", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Noa Lang", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "JPN": [
    { nome: "Kosuke Nakamura", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Takehiro Tomiyasu", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Shogo Taniguchi", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Ko Itakura", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Yuta Nakayama", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Hidemasa Morita", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Wataru Endō", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Ritsu Dōan", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Daizen Maeda", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Junya Itō", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Kyōgo Furuhashi", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Keisuke Osako", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Seiya Maikuma", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Tsuyoshi Watanabe", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Ryō Hatsuse", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Koki Machida", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Ao Tanaka", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Daichi Kamada", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Kaoru Mitoma", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Takefusa Kubo", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Takumu Kawamura", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Keito Nakamura", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Zion Suzuki", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Yuki Sōma", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Takumi Minamino", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Ayase Ueda", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "SWE": [
    { nome: "Robin Olsen", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Ludwig Augustinsson", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Victor Lindelöf", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Filip Helander", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Emil Holm", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Albin Ekdal", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Jens Cajuste", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Mattias Svanberg", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Alexander Isak", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Emil Forsberg", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Viktor Gyökeres", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Kristoffer Nordfeldt", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Johan Håkansson", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Isak Hien", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Hjalmar Ekdal", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Linus Wahlqvist", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Hugo Larsson", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Samuel Gustafson", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Anton Salétros", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Yasin Ayari", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Anthony Elanga", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Dejan Kulusevski", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Viktor Johansson", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Jesper Karlström", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Simon Olsson", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Gustaf Nilsson", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "TUN": [
    { nome: "Béchir Ben Saïd", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Ali Abdi", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Dylan Bronn", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Mohamed Dräger", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Yassine Meriah", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Ellyes Skhiri", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Aïssa Laïdouni", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Ferjani Sassi", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Yoann Touzghar", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Wahbi Khazri", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Seifeddine Jaziri", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Mouez Hassen", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Ali Maâloul", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Nader Ghandri", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Bilel Ifa", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Amenallah Memmich", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Hannibal Mejbri", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Saad Yacine", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Haythem Jouini", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Firas Ben Larbi", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Elias Achouri", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Montassar Trabelsi", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Aymen Dahmen", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Taha Yassine Khenissi", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Yan Valery", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Anis Ben Slimane", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "BEL": [
    { nome: "Koen Casteels", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Zeno Debast", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Arthur Theate", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Wout Faes", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Ameen Al-Dakhil", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Axel Witsel", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Kevin De Bruyne", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Youri Tielemans", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Romelu Lukaku", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Jérémy Doku", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Lois Openda", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Thomas Kaminski", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Matz Sels", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Maxim De Cuyper", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Timothy Castagne", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Thomas Meunier", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Hans Vanaken", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Orel Mangala", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Leandro Trossard", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Arthur Vermeeren", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Dodi Lukebakio", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Yannick Carrasco", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Davy Roef", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Dries Mertens", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Amadou Onana", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Johan Bakayoko", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "EGY": [
    { nome: "Mohamed El Shenawy", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Mohamed Hany", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Ali Gabr", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Rami Rabia", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Ahmed Hegazy", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Mohamed Elneny", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Mahmoud Trezeguet", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Hamdi Fathi", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Ahmed Hassan Kok", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Mohamed Salah", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Omar Marmoush", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Mohamed Abou Gabal", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Mohamed Sherif", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Hussein El Shahat", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Karim Hafez", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Ahmed Samy", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Emam Ashour", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Marwan Attia", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Mostafa Fathi", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Ahmed Nabil Koka", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Mostafa Mohamed", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Ibrahim Adel", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Mahmoud Gad", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Mohamed Abdelmonem", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Nabil Emad", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Osama Faisal", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "IRI": [
    { nome: "Alireza Beiranvand", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Sadegh Moharrami", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Ehsan Hajsafi", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Shojae Khalilzadeh", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Milad Mohammadi", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Saeid Ezatolahi", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Alireza Jahanbakhsh", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Saman Ghoddos", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Mehdi Taremi", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Karim Ansarifard", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Sardar Azmoun", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Amir Abedzadeh", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Hossein Kanaanizadegan", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Majid Hosseini", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Ramin Rezaeian", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Amin Hazbavi", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Mohammad Mohebi", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Ahmad Nourollahi", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Ali Gholizadeh", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Mohammad Karimi", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Shahriar Moghanlou", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Allahyar Sayyadmanesh", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Payam Niazmand", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Mehdi Ghayedi", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Omid Noorafkan", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Mohammad Hosseinnejad", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "NZL": [
    { nome: "Oliver Sail", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Thomas Smith", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Francis de Vries", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Michael Boxall", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Tyler Bindon", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Joe Bell", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Marko Stamenić", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Matthew Garbett", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Chris Wood", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "André de Jong", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Elijah Just", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Max Crocombe", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Tim Payne", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Bill Tuiloma", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Nando Pijnaker", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Kyle Adams", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Alex Rufer", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Moses Dyer", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Finn Surman", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Liam Gillion", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Ben Waine", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Alex Greive", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Nik Tzanev", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Kosta Barbarouses", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Callum McCowatt", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Max Mata", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "ESP": [
    { nome: "Unai Simón", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Dani Carvajal", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Robin Le Normand", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Nacho", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Álex Grimaldo", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Rodri", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Mikel Merino", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Fabián Ruiz", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Álvaro Morata", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Lamine Yamal", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Nico Williams", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "David Raya", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Aymeric Laporte", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Pau Cubarsí", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Jesús Navas", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Dani Vivian", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Pedri", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Martín Zubimendi", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Aleix García", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Mikel Oyarzabal", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Ferran Torres", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Dani Olmo", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Álex Remiro", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Ayoze Pérez", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Sergio Gómez", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Joselu", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "CPV": [
    { nome: "Josimar Dias", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Duk", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Carlos Ponck", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Roberto Lopes", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Logan Costa", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Patrick Andrade", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Jamiro Monteiro", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Nuno Borges", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Youssef Belaïli", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Jovane Cabral", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Garridon Mendonça", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Kevin Sousa", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Dylan Silva", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Delmiro Nogueira", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Jeffry Fortes", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Lucas Covane", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Rui Mendes", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Edilson Borges", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Délcio Moreno", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Renato Sanches", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Gilson Tavares", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Hélio Varela", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Márcio Sousa", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Bebé", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Ravy Varela", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Cléton Silva", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "URU": [
    { nome: "Sergio Rochet", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "José María Giménez", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Ronald Araújo", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Santiago Bueno", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Matías Viña", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Federico Valverde", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Nicolás De La Cruz", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Giorgian De Arrascaeta", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Luis Suárez", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Darwin Núñez", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Facundo Pellistri", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Franco Israel", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Guillermo Varela", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Sebastián Cáceres", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Lucas Olaza", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Bruno Méndez", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Manuel Ugarte", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Rodrigo Bentancur", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Emiliano Martínez", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Brian Ocampo", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Maximiliano Gómez", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Cristian Olivera", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Santiago Mele", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Facundo Torres", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Felipe Carballo", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Luciano Rodríguez", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "KSA": [
    { nome: "Mohammed Al-Owais", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Fawaz Al-Sqoor", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Yasser Al-Shahrani", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Ayman Yahya", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Ali Al-Boleahi", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Mohamed Kanno", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Salman Al-Faraj", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Abdulellah Al-Malki", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Firas Al-Buraikan", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Salem Al-Dawsari", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Haroune Camara", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Nawaf Al-Aqidi", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Zakaria Hawsawi", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Sultan Al-Ghanam", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Hassan Tambakti", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Saud Abdulhamid", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Abdulaziz Al-Bishi", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Nasser Al-Dawsari", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Fahad Al-Muwallad", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Hattan Bahebri", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Abdullah Radif", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Marwan Al-Sahafi", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Ahmed Al-Kassar", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Mishari Al-Nemer", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Al-Hassan Ghareeb", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Mohammed Maran", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "FRA": [
    { nome: "Mike Maignan", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Benjamin Pavard", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Jules Koundé", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Dayot Upamecano", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Théo Hernandez", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Eduardo Camavinga", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Antoine Griezmann", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Aurélien Tchouaméni", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Olivier Giroud", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Kylian Mbappé", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Ousmane Dembélé", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Brice Samba", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "William Saliba", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Lucas Hernández", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Ibrahima Konaté", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Jonathan Clauss", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Youssouf Fofana", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Adrien Rabiot", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Khéphren Thuram", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Warren Zaïre-Emery", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Randal Kolo Muani", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Kingsley Coman", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Alphonse Areola", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Marcus Thuram", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Boubacar Kamara", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Christopher Nkunku", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "NOR": [
    { nome: "Ørjan Nyland", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Marcus Holmgren Pedersen", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Leo Skiri Østigård", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Stefan Strandberg", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Stian Gregersen", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Kristian Thorstvedt", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Morten Thorsby", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Sander Berge", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Erling Haaland", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Martin Ødegaard", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Alexander Sørloth", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Mathias Dyngeland", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "David Møller Wolfe", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Julian Ryerson", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Jesper Daland", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Andreas Hanche-Olsen", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Patrick Berg", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Hugo Vetlesen", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Mohamed Elyounoussi", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Ola Brynhildsen", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Jørgen Strand Larsen", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Johan Hove", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Viljar Myhra", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Tobias Børkeeiet", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Markus Henriksen", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Oscar Bobb", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "SEN": [
    { nome: "Édouard Mendy", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Krépin Diatta", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Kalidou Koulibaly", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Moussa Niakhaté", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Ismail Jakobs", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Nampalys Mendy", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Sadio Mané", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Pape Matar Sarr", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Boulaye Dia", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Ismaïla Sarr", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Nicolas Jackson", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Seny Dieng", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Abdou Diallo", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Fodé Ballo-Touré", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Moustapha Name", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Formose Mendy", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Pathé Ciss", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Idrissa Gueye", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Pape Gueye", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Habib Diarra", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Mame Diouf", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Abdallah Sima", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Mory Diaw", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Cherif Ndiaye", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Assan Ceesay", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Iliman Ndiaye", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "IRQ": [
    { nome: "Jalal Hassan", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Ali Adnan", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Rebin Sulaka", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Saad Natiq", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Zidane Iqbal", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Amir Al-Ammari", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Ousama Rashid", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Ibrahim Bayesh", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Ali Al-Hamadi", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Mohanad Ali", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Aymen Hussein", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Ahmed Basil", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Dhurgham Ismail", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Merchas Doski", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Maithm Jabbar", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Ahmed Yahya", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Ali Jasim", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Mohammed Sadeq", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Mohanad Jeahze", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Youssef Amyn", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Hussein Ali", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Ahmed Yasin", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Hasan Ahmed", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Sajad Jassim", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Yousif Ayedh", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Karrar Al-Mukhtar", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "ARG": [
    { nome: "Emiliano Martínez", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Nahuel Molina", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Cristian Romero", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Germán Pezzella", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Lisandro Martínez", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Leandro Paredes", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Rodrigo De Paul", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Enzo Fernández", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Julián Álvarez", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Lionel Messi", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Ángel Di María", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Gerónimo Rulli", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Nicolás Tagliafico", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Lucas Martínez Quarta", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Nicolás Otamendi", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Gonzalo Montiel", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Alexis Mac Allister", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Guido Rodríguez", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Nicolás González", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Giovani Lo Celso", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Paulo Dybala", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Lautaro Martínez", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Franco Armani", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Alejandro Garnacho", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Ezequiel Palacios", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Ángel Correa", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "AUT": [
    { nome: "Alexander Schlager", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Max Wöber", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "David Alaba", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Kevin Danso", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Phillipp Mwene", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Nicolas Seiwald", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Marcel Sabitzer", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Christoph Baumgartner", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Marko Arnautović", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Michael Gregoritsch", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Marcel Hartel", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Patrick Pentz", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Gernot Trauner", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Philipp Lienhart", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Stefan Posch", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Marvin Potzmann", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Xaver Schlager", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Florian Grillitsch", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Romano Schmid", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Konrad Laimer", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Andreas Weimann", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Karim Onisiwo", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Niklas Hedl", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Junior Adamu", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Florian Kainz", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Christoph Lang", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "ALG": [
    { nome: "Raïs M'Bolhi", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Aïssa Mandi", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Ramy Bensebaini", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Mohamed Amine Tougai", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Victor Correia", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Adem Zorgane", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Riyad Mahrez", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Houssem Aouar", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Islam Slimani", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Sofiane Feghouli", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Andy Delort", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Anthony Mandrea", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Rayan Aït-Nouri", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Zineddine Belaïd", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Ahmed Touba", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Kevin Guitoun", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Yacine Adli", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Ismaël Bennacer", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Zakaria Naidji", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Farid Boulaya", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Youcef Belaïli", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Mohamed El Amine Amoura", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Oussama Benbot", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Saïd Benrahma", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Hicham Boudaoui", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Baghdad Bounedjah", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "JOR": [
    { nome: "Yazeed Abu Layla", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Mohammad Abu Hasheesh", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Abdallah Nasib", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Yazan Al-Arab", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Hadi Al-Hourani", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Mohammad Al-Mawajdeh", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Mohammad Abu Zrayq", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Noor Al-Rawabdeh", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Yazan Al-Naimat", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Musa Al-Taamari", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Ali Alwan", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Ahmad Al-Juaidi", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Ihsan Haddad", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Anas Bani Yassen", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Saeed Al-Rosan", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Yousef Al-Souliman", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Rajaei Ayed", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Saleh Rateb", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Mohammad Al-Zu'bi", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Obaida Al-Samarneh", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Hamza Al-Dardour", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Ahmed Al-Sheyab", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Abdallah Al-Fakhouri", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Mohammad Aburiziq", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Fadi Awad", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Alaa Al-Shaqran", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "COL": [
    { nome: "David Ospina", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Daniel Muñoz", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Jhon Janer Lucumí", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Yerry Mina", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Cristian Borja", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Kevin Castaño", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "James Rodríguez", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Jhon Arias", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Rafael Santos Borré", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Juan Fernando Quintero", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Luis Díaz", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Camilo Vargas", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Santiago Arias", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Carlos Cuesta", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Johan Mojica", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Andrés Llinás", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Richard Ríos", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Jéfferson Lerma", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Yaser Asprilla", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Matheus Uribe", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Miguel Borja", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Jhon Durán", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Álvaro Montero", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Luis Sinisterra", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Gustavo Cuéllar", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Mateo Cassierra", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "POR": [
    { nome: "Diogo Costa", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Nélson Semedo", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Rúben Dias", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Gonçalo Inácio", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Diogo Dalot", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "João Palhinha", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Bruno Fernandes", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Bernardo Silva", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Cristiano Ronaldo", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "João Félix", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Rafael Leão", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "José Sá", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Nuno Tavares", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Pepe", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Rúben Neves", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "João Cancelo", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Vitinha", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Otávio", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Matheus Nunes", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Danilo Pereira", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Gonçalo Ramos", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Diogo Jota", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Rui Silva", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Pedro Neto", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "João Neves", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Francisco Conceição", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "COD": [
    { nome: "Lion Mpasi", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Brian Bayeye", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Chancel Mbemba", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Rochel Koffi", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Arthur Masuaku", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Samuel Moutoussamy", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Grady Diangana", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Gaël Kakuta", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Pelly Ruddock Mpanzu", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Yoane Wissa", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Simon Banza", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Baggio Siadi", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Joris Kayembe", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Henri Boma", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Dylan Batubinsika", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Merveil Mandefu", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Aaron Tshibola", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "William Balikwisha", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Omenuke Mfulu", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Théo Bongonda", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Cédric Bakambu", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Fiston Kalala Mayele", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Timothy Fayulu", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Jonathan Bolingi", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Charles Ondo", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Meschack Elia", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "UZB": [
    { nome: "Utkir Yusupov", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Khusniddin Alikulov", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Farrukh Sayfiev", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Eldorbek Begimov", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Rustamjon Ashurmatov", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Jamshid Iskanderov", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Otabek Shukurov", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Azizbek Turgunboev", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Eldor Shomurodov", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Jaloliddin Masharipov", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Oston Urunov", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Abduvakhid Nematov", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Sherzod Nasrullaev", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Sardor Mirzaev", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Abbosbek Faizullaev", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Mukhammadkodir Khamraliev", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Akmal Mozgovoy", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Abdulla Abdullaev", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Odiljon Hamrobekov", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Khojiakbar Alijonov", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Bobur Abdikholikov", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Azizbek Amonov", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Botirali Ergashev", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Khusayin Norchaev", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Dostonbek Khamdamov", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Shokhboz Umarov", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "ENG": [
    { nome: "Jordan Pickford", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Kyle Walker", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "John Stones", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Harry Maguire", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Luke Shaw", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Declan Rice", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Bukayo Saka", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Jude Bellingham", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Harry Kane", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Phil Foden", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Cole Palmer", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Aaron Ramsdale", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Kieran Trippier", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Lewis Dunk", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Marc Guéhi", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Reece James", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Conor Gallagher", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Kobbie Mainoo", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "James Maddison", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Mason Mount", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Jarrod Bowen", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Marcus Rashford", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Dean Henderson", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Ivan Toney", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Eberechi Eze", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Anthony Gordon", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "CRO": [
    { nome: "Dominik Livaković", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Josip Stanišić", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Joško Gvardiol", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Martin Erlić", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Borna Barišić", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Luka Modrić", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Mateo Kovačić", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Marcel Brozović", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Andrej Kramarić", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Ivan Perišić", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Bruno Petković", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Nediljko Labrović", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Josip Juranović", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Marin Pongračić", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Duje Ćaleta-Car", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Borna Sosa", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Nikola Vlašić", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Lovro Majer", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Mario Pašalić", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Luka Sučić", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Ante Budimir", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Marco Livaja", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Ivan Ivušić", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Josip Brekalo", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Kristijan Jakić", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Ivan Brnić", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "GHA": [
    { nome: "Lawrence Ati-Zigi", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Alidu Seidu", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "Mohammed Salisu", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Daniel Amartey", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Gideon Mensah", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Thomas Partey", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Mohammed Kudus", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Majeed Ashimeru", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "Jordan Ayew", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "André Ayew", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Iñaki Williams", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "Richard Ofori", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Abdul Fatawu Hamidu", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Joseph Aidoo", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Alexander Djiku", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Tariq Lamptey", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "Iddrisu Baba", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Elisha Owusu", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Salis Abdul Samed", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Abu Francis", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Antoine Semenyo", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Ernest Nuamah", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Frederick Asare", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Osman Bukari", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Kamaldeen Sulemana", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Jonathan Sowah", posicao: "Atacante", numeroCamisa: 26 },
  ],
  "PAN": [
    { nome: "Orlando Mosquera", posicao: "Goleiro", numeroCamisa: 1 },
    { nome: "Michael Murillo", posicao: "Defensor", numeroCamisa: 2 },
    { nome: "José Córdoba", posicao: "Defensor", numeroCamisa: 3 },
    { nome: "Fidel Escobar", posicao: "Defensor", numeroCamisa: 4 },
    { nome: "Jorge Gutiérrez", posicao: "Defensor", numeroCamisa: 5 },
    { nome: "Aníbal Godoy", posicao: "Meio-campista", numeroCamisa: 6 },
    { nome: "Cristian Martínez", posicao: "Meio-campista", numeroCamisa: 7 },
    { nome: "Adalberto Carrasquilla", posicao: "Meio-campista", numeroCamisa: 8 },
    { nome: "José Fajardo", posicao: "Atacante", numeroCamisa: 9 },
    { nome: "Ismael Díaz", posicao: "Atacante", numeroCamisa: 10 },
    { nome: "Cecilio Waterman", posicao: "Atacante", numeroCamisa: 11 },
    { nome: "César Samudio", posicao: "Goleiro", numeroCamisa: 12 },
    { nome: "Eduardo Anderson", posicao: "Defensor", numeroCamisa: 13 },
    { nome: "Roderick Miller", posicao: "Defensor", numeroCamisa: 14 },
    { nome: "Eric Davis", posicao: "Defensor", numeroCamisa: 15 },
    { nome: "Carlos Harvey", posicao: "Defensor", numeroCamisa: 16 },
    { nome: "José Luis Rodríguez", posicao: "Meio-campista", numeroCamisa: 17 },
    { nome: "Abdiel Arroyo", posicao: "Meio-campista", numeroCamisa: 18 },
    { nome: "Irvin Ábrego", posicao: "Meio-campista", numeroCamisa: 19 },
    { nome: "Yanis Cárdenas", posicao: "Meio-campista", numeroCamisa: 20 },
    { nome: "Alfredo Stephens", posicao: "Atacante", numeroCamisa: 21 },
    { nome: "Azarías Londoño", posicao: "Atacante", numeroCamisa: 22 },
    { nome: "Eddie Roberts", posicao: "Goleiro", numeroCamisa: 23 },
    { nome: "Jorman Aguilar", posicao: "Atacante", numeroCamisa: 24 },
    { nome: "Martín Gerald", posicao: "Meio-campista", numeroCamisa: 25 },
    { nome: "Rolando Botello", posicao: "Atacante", numeroCamisa: 26 },
  ],
};
